name: the record of Hoey's Learning
url: http://huangyuanzhen.github.io
title: the record of Yuanzhen's Learning
email: huangyuanzhen7728@gmail.com
description: ./_site
lsi:      false
safe:     false
baseurl: ""
github_username:  huangyuanzhen
encoding: utf-8
# Build settings

markdown: redcarpet
markdown: kramdown
kramdown:
  input: GFM
pygments:    true
highlighter: pygments

post_defaults:
  layout: post

permalink: /blog/:year/:month/:day/:title
