name: Jasminehyz's self-introduction
url: http://Jasminehyz.github.io
title: Jasminehyz's self-introduction
email: huangyuanzhen7728@gmail.com
lsi:      false
safe:     false
baseurl: ""
github_username:  Jasminehyz
encoding: utf-8
# Build settings

markdown: redcarpet
markdown: kramdown
kramdown:
  input: GFM
